- endpoint-sec-sys/Cargo.toml
- endpoint-sec/Cargo.toml
Was missing for initial release.
> Add missing link to repository on endpoint-sec(-sys)

- endpoint-sec-sys/src/client.rs
- endpoint-sec-sys/src/message.rs
- endpoint-sec/src/client.rs
- endpoint-sec/src/message.rs
Fix almost all warnings (except macro based ones) because of link to feature gated functions.
> Fix warnings on doc with default features

- Cargo.toml
See https://github.com/HarfangLab/endpoint-sec/pull/7/files#r1280891213 for an instance of the problem
> deps: less precise versions to avoid dep bots updating patch versions

- endpoint-sec-sys/Cargo.toml
- endpoint-sec/Cargo.toml
This enables "jump to definition" functionality in the
source code view of rustdoc.
> docs: add --generate-link-to-definition flag

- endpoint-sec-sys/src/lib.rs
This lint came with the new Rust version
> fix: better implementation of `Clone` for `ShouldNotBeNull`

- .github/workflows/build.yaml
- ci: Use better defined vars for concurrency detection
- ci: Only run branch CI on main, so that local dev branches don't run all jobs twice
> ci: Run with a smarter config to avoid double-runs for local branches

- Cargo.lock
- Cargo.toml
- appveyor.yml
- endpoint-sec/Cargo.toml
- endpoint-sec/src/client.rs
- endpoint-sec/src/lib.rs
- endpoint-sec/tests/ui.rs
- endpoint-sec/tests/ui/test_client_cannot_outlive_handler.rs
- endpoint-sec/tests/ui/test_client_cannot_outlive_handler.stderr
This allows constructing a client locally and have it interact inside a `std::thread::scope` for example,
depending on non-`'static` data.
I added a trybuild test to ensure we don't allow the client to outlive the handler.
This is breaking change and will need a 0.3.0
> feat: Don't require the closure passed to `Client` to be `'static`

- Cargo.lock
- Cargo.toml
- Justfile
- endpoint-sec/tests/ui/test_client_cannot_be_smuggled_out.rs
- endpoint-sec/tests/ui/test_client_cannot_be_smuggled_out.stderr
- tests: add compile test to ensure `Client`s cannot be swapped
- release: Add Justfile to help with publishing
- release: version 0.3.0
> release: v0.3.0

- endpoint-sec/src/event/event_close.rs
- endpoint-sec/src/event/event_exchangedata.rs
- endpoint-sec/src/event/event_exec.rs
- endpoint-sec/src/event/event_file_provider_materialize.rs
- endpoint-sec/src/event/event_fork.rs
- endpoint-sec/src/event/event_get_task.rs
- endpoint-sec/src/event/event_mmap.rs
- endpoint-sec/src/event/event_open.rs
- endpoint-sec/src/event/event_signal.rs
- endpoint-sec/src/event/event_trace.rs
- endpoint-sec/src/event/event_unlink.rs
A quick fix for objects that were restrained to the lifetime of their event's `&self` instead of the (wider) lifetime of the whole `Message`.
I'll publish a new version `0.3.1` just after, since it's not a breaking change I think: lifetimes are wider, nothing that was possible before is impossible now.
> fix: Extend lifetime for objects that were unnecessarily restrained to that of `&self`

- endpoint-sec/src/client.rs
- endpoint-sec/tests/client.rs
Client::new would automatically free the block_handler, which would also free the closure. This was initially thought to be fine as es_new_client should be cloning the block. However, the ConcreteBlock implementation of copy does not actually do a deep clone - instead it merely does a memmove of the closure data.
As such, we need to make sure we don't run the destructore on block_handler.
> Avoid freeing block_handler too early

- endpoint-sec/src/event/event_login_login.rs
- endpoint-sec/src/event/event_openssh_login.rs
- endpoint-sec/src/event/event_su.rs
- endpoint-sec/src/event/event_sudo.rs
tldr: the code inside bool::then_some is always executed, but the code in the closure from bool::then is only executed if is true.
This is UB, because the bool::then_some is a function that takes a bool and a generic value, because of that, the value inside of it is always evaluated, independent if the bool is true/false.
it's clear if the desugarize the syntax:
```rust
// first we get the true/false for the condition
let cond: bool = self.success() && self.has_to_uid();
// then we evaluate the expression to pass the value as parameter
// UB here, the is executed always, independent of the cond being true/false
let value = unsafe { self.raw.to_uid.uid };
// then we call the function `bool::then_some`.
bool::then_some(cond, value)
```
The solution is simply change it to bool::then, because …
> Fix UB on EventSu::to_uid

- endpoint-sec-sys/src/message.rs
When using the default feature, the FFI structure for es_message_t was wrong (a field in the middle was cfg'd out, causing everything to be offset by 8 bytes).
To fix this issue, we simply remove the wrong cfg, fixing the es_message_t structure.
Fixes #33 
I did a quick review of the other structures, but they seem to be OK, all the cfgs are at the end, and always ordered from oldest to newest.
Note that I did not change the seq_num() accessor, which is cfg'd to be accessible only on macos_10_15_4+. I think that's correct enough.
> Fix segfault when using default feature

- Cargo.lock
- Cargo.toml
Changes:
- Fix segfault when using default feature due to broken FFI definition of `es_message_t`.
Commit list: [v0.3.3..release-0.3.4](https://github.com/HarfangLab/endpoint-sec/compare/v0.3.3...roblabla:endpoint-sec:release-0.3.4)
> Release 0.3.4

- .github/workflows/build.yaml
- appveyor.yml
I submit this PR to use the latest macOS 14 runner in CI
> ci: use the macos 14 runner

- endpoint-sec/tests/ui/test_client_cannot_be_smuggled_out.stderr
- endpoint-sec/tests/ui/test_client_cannot_outlive_handler.stderr
This should help fix the current build status on `main`. The changes seem to only be due to the more recent Rust versions, but the core of the errors is still there.
> Chore(test): Update UI fixtures

- .github/workflows/build.yaml
- endpoint-sec-sys/src/lib.rs
- endpoint-sec/src/acl.rs
- endpoint-sec/src/event/event_login_login.rs
- endpoint-sec/src/event/event_openssh_login.rs
- endpoint-sec/src/event/event_su.rs
- endpoint-sec/src/event/event_sudo.rs
Currently, Clippy in only ran in CI to fail on errors, not on warnings, which is not ideal. This therefore fixes warnings currently triggered on `main` and adds `-D warnings` to the CI execution of Clippy in order to enforce warnings in the future.
> CI: Enforce clippy

- .github/workflows/build.yaml
- Cargo.lock
- Cargo.toml
- README.md
Dependency update that requires bumping the MSRV to 1.70. This should supersede #49.
> Chore(deps): Bump trybuild to latest version and MSRV to 1.70

- Cargo.lock
- Cargo.toml
- endpoint-sec-sys/src/client.rs
- endpoint-sec/src/client.rs
Bumps both to their respective latest version.
Special care should be taken reviewing this one in particular:
* `Block` transitioned from taking two type arguments in the form of `<(In1, In2, ...), Out>` to a single `dyn` one: `<dyn Fn(In1, In2, ...) -> Out>`. A lifetime can be added to this, making the block non-`'static`. This was required for `endpoint_sec_sys::client::es_handler_block_t`, which could be a breaking change. However, it is not in `endpoint-sec` since inference succeeds there.
* `ConcreteBlock` was renamed to `StackBlock` and now requires the passed function to be `Clone`, which in our single use of it was too restrictive for callers and would have required changing tests accordingly so that all types involved in the given function be `Clone` as well. In order to avoid …
> Chore(deps): Bump block2 and objc2

- endpoint-sec-sys/src/additional.rs
- endpoint-sec-sys/src/client.rs
- endpoint-sec/tests/ui.rs
Unblock the CI:
* Remove the non-existent feature `cfg` gate.
* Fix the recent `clippy::doc_lazy_continuation` by adding the few missing indentations.
> Fix warnings

- .github/workflows/build.yaml
macOS 11 is not supported by [GitHub Actions](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) anymore. Therefore, make the jobs that used to run on 11 run on 12 instead. It should finally unblock the CI this time.
> CI: Bump macOS runners to at least v12
